### ISSUE TITLE
In english pretty please?

### ISSUE THREAD

**Issue by paulharris** [iwiwi/radix-heap#1]
Hi,

This implementation is so far the only implementation of a radix_heap that I've seen via google.
I first saw the algorithm described here:
http://ssp.impulsetrain.com/radix-heap.html

It looks very cool, but I am wondering why we don't see the radix_heap implemented more widely, or even in the STL.

So I was hoping you could provide a translation in English.
I used translate.google.com, and I suppose that is enough, but this library looks really neat and it would be good if the readme was in english too, same as the code.

Nice work,
Paul

**Comment by iwiwi** [comment]
Hi Paul,

Thank you for your interest in my radix-heap implementation. I will add an English README in (hopefully) a few days. Please stay tuned :)

Best,
Takuya

**Comment by paulharris** [comment]
Great!   Thanks, this is a great explanation
